behaviors:
  HiderAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.003
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 100000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 4
      save_replay_buffer: false
      init_entcoef: 0.05
      reward_signal_steps_per_update: 4
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    max_steps: 200000
    time_horizon: 64
    summary_freq: 10000
